<?xml version="1.0" encoding="UTF-8"?>
<!-- Initial comment -->
<!DOCTYPE people [
<!ELEMENT people (person*)>
<!ELEMENT person (name, job*)>
<!ATTLIST person born CDATA #IMPLIED
                 deceased CDATA #IMPLIED>
<!ELEMENT name (firstname, lastname)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT job (#PCDATA)>
]>
<people>
 <!-- This ist the first person! -->
 <person born="1914" deceased="1952">
  <name>
   <firstname>
     Alan
   </firstname>
   <lastname>
     Turing
   </lastname>
  </name>
  <job>
   Mathematician
  </job>
  <job>
    Compu<!-- Splitting comment -->ter Scientist
  </job>
 </person>
 <person born="1916" deceased="1988">
  <name>
   <firstname>Richard</firstname>
   <lastname>Feynman</lastname>
  </name>
  <job>Physicist</job>
 </person>
 <!-- This was the last person -->
</people>
