=== svarthaj/net-based/assign-009/bank-schema.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
						xmlns:xml="http://www.w3.org/XML/1998/namespace" >
						<!-- not sure about namespaces
						xmlns:c="http://acme-bank.com/bank/checking"
						xmlns:s="http://acme-bank.com/bank/savings" -->
	<!-- Used substitutionGroup to represent the two kinds of accounts -->
  <xsd:element name="account"/>
	<xsd:element name="savings_account" substitutionGroup="account">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="balance">
					<xsd:simpleType>
						<xsd:restriction base="xsd:integer">
							<xsd:minInclusive value="-5000"/>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:element>
			</xsd:sequence>
			<xsd:attribute name="id" type="xsd:string" use="required"/>
			<xsd:attribute name="interest" type="xsd:decimal" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="checking_account" substitutionGroup="account">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="balance">
					<xsd:simpleType>
						<xsd:restriction base="xsd:integer">
							<xsd:minInclusive value="-5000"/>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:element>
			</xsd:sequence>
			<xsd:attribute name="id" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>

  <xsd:element name="bank">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="accounts" minOccurs="1" maxOccurs="1">
					<xsd:complexType>
						<xsd:sequence>
							<!-- Reference to the account group defined before -->
							<xsd:element ref="account" maxOccurs="unbounded"/>
						</xsd:sequence>
					</xsd:complexType>
					<!-- I'm not sure how to deal with keys and substitutionGroup -->
					<xsd:key name="idKey">
						<xsd:selector xpath="./bank/accounts/savings_accounts/savings_account|./bank/accounts/checking_accounts/checking_account"/>
						<xsd:field xpath="@id"/>
					</xsd:key>
					<xsd:keyref name="foreignKey" refer="idKey">
						<xsd:selector xpath="./bank/customer_accounts"/>
						<xsd:field xpath="@ac_id"/>
					</xsd:keyref>
				</xsd:element>
				<xsd:element name="customers" minOccurs="1" maxOccurs="1">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="customer" minOccurs="1" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="name" type="xsd:string"/>
										<xsd:element name="address" type="xsd:string" />
									</xsd:sequence>
									<xsd:attribute name="id" type="xsd:ID" use="required" />
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="customer_accounts" minOccurs="1" maxOccurs="1">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="customer_account" minOccurs="1" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:attribute name="c_id" type="xsd:IDREF" use="required" />
									<xsd:attribute name="ac_id" use="required" />
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
					<!--  key and keyref and change the ID IDREF by it to make it easier for next assignments -->
					<xsd:unique name="ac_unique">
						<xsd:selector xpath="customer_account"/>
						<xsd:field xpath="@ac_id"/>
					</xsd:unique>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== svarthaj/net-based/assign-009/Task1.2/bank2.xml
<?xml version="1.0" encoding="UTF-8"?>
<bank xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://acme-bank.com/bank bank-schema.xsd">
  
  <accounts>
    <savings_account id="a1" interest="0.03" xmlns="http://acme-bank.com/bank/savings">
      <balance>2500</balance>
    </savings_account>   
    <savings_account id="a2" interest="0.03" xmlns="http://acme-bank.com/bank/savings">
      <balance>15075</balance>
    </savings_account>  
    <checking_account id="a3" xmlns="http://acme-bank.com/bank/checking">
      <balance>4025</balance>
    </checking_account>
    <checking_account id="a4" xmlns="http://acme-bank.com/bank/checking">
      <balance>-125</balance>
    </checking_account>
    <checking_account id="a5" xmlns="http://acme-bank.com/bank/checking">
      <balance>325</balance>
    </checking_account>  
  </accounts>

  <customers>
    <customer id="c1">
      <name>Ben Richerdson</name>
      <address>Park Drive 2</address>
    </customer>
    <customer id="c2">
      <name>Marc Wretcher</name>
      <address>Mill Drive 75</address>
    </customer>
    <customer id="c3">
      <name>Angel Steady</name>
      <address>Lake Sight 15</address>
    </customer>
  </customers>
  
  <customer_accounts>
    <customer_account c_id="c1" ac_id="a2"/>
    <customer_account c_id="c1" ac_id="a3"/>
    <customer_account c_id="c2" ac_id="a4"/>
    <customer_account c_id="c3" ac_id="a1"/>
    <customer_account c_id="c3" ac_id="a5"/>
  </customer_accounts>
  
</bank>
